### ISSUE TITLE
feat: Trigger retraining on CloudWatch alarm drift detection

### ISSUE THREAD

**Issue by brightsparc** [aws-samples/amazon-sagemaker-safe-deployment-pipeline#15]
Alarms are currently created when drift is detected, but need to add a cloud watch event to start pipeline.

This can be done by creating a role with permission to start the code pipeline.   Note there is no ARN for the [AWS::CodePipeline::Pipeline](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html) resource, so need format the name.

```
  CloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub mlops-${ModelName}-cwe-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: "mlops-cwe-pipeline-execution"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${DeployPipeline}"
```

To start the pipeline, you just need to specify the Target Arn

```
  CloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.cloudwatch
        detail-type:
          - "CloudWatch Alarm State Change"
        detail:
          alarmName:
            - !Sub mlops-${ModelName}-metric-gt-threshold
          state:
            value: 
              - "ALARM"
      Targets:
        -
          Arn: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${DeployPipeline}"
          RoleArn: !GetAtt CloudWatchEventRole.Arn
          Id: !Sub codepipeline-${DeployPipeline}
```

[see docs](https://docs.aws.amazon.com/codepipeline/latest/userguide/create-cloudtrail-S3-source-cfn.html)
