### ISSUE TITLE
feat: Update prod deploy to enable DataCaptureConfig on create

### ISSUE THREAD

**Issue by brightsparc** [aws-samples/amazon-sagemaker-safe-deployment-pipeline#5]
CloudFormation now supports included DataCaptureConfig as part of EndpointConfig which can removed the need to have an explicit step to enable data config after an endpoint is created.

The deploy-model-prd.yml can be extended  with the following configuration.

```
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      DataCaptureConfig:
        CaptureContentTypeHeader:
          CsvContentTypes:
            - "text/csv"
          JsonContentTypes:
            - "application/json"
        CaptureOptions:
          - CaptureMode: Input
          - CaptureMode: Output
        DestinationS3Uri: !Sub s3://sagemaker-${AWS::Region}-${AWS::AccountId}/${ModelName}/datacapture
        EnableCapture: True
        InitialSamplingPercentage: 100
        KmsKeyId: !Ref KmsKeyId
```

See also [DataCaptureConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-endpointconfig-datacaptureconfig.html) docs
